services:
  - name: "conversations db backup"
    type: cron
    schedule: "0 3 * * *"
    region: oregon
    env: docker
    plan: standard
    dockerfilePath: ./Dockerfile
    autoDeploy: false
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: "conversations db"
          property: connectionString
      - fromGroup: "Conversations"

